name: ci

on: ["pull_request", "push"]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer (PHP ${{ matrix.php }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.1'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: php-cs-fixer, cs2pr

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix --format=checkstyle | cs2pr

  psalm:
    name: Psalm (PHP ${{ matrix.php }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.1'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Run Composer
        run: composer update --no-interaction --no-progress

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github

  tests:
    name: "tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2

      - name: "caching dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.operating-system }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.operating-system }}"

      - name: "installing lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"

      - name: "installing highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "installing phpunit"
        run: "php vendor/bin/simple-phpunit install"

      - name: "running tests"
        if: ${{ matrix.dependencies == 'lowest' }}
        env:
          SYMFONY_DEPRECATIONS_HELPER: disabled=1
        run: "php vendor/bin/simple-phpunit"

      - name: "running tests"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "php vendor/bin/simple-phpunit"
